### ISSUE TITLE
[Bug] Pagination returns to first page when going back after navigating away from a page

### ISSUE THREAD

**Issue by sjclayton** [curtwagner1984/YAPO#14]
I think this needs to be fixed, as navigating back from a page after clicking on a link and having it reset to the 1st page automatically is a very large annoyance. An actual issue from my standpoint, therefore I am considering this a bug, as opposed to a feature request.

**Comment by curtwagner1984** [comment]
First of all let's see if I understand you correctly, by 'navigating back' You mean that after you click on a link and are redirected to another page, you click 'back' on the browser?

This issue is a bit complex as we need to find a way to differentiate between when you just navigate to the page (And the pagination should be on the first page) and when you coming back to a page using the back button.

It's an interesting problem.

There is a way to store session information, it's an Angular module called ngStorage. I use it to to store the gridview preference and the number of items per page setting and also the info to the next and prev items when in scene detail view.  The functions that are using it are found in 'helperService' under app.services.js

I'm thinking it's possible to use it to store the current page. However there is another problem. There is a need to differentiate between when you just in a scene-list (from the main menu) and when you are in a scene-list inside of actor-details. Because if you remember that a scene list should be on page 3 and then go to an actor that has only 2 scenes, page 3 will be empty and no scenes will be shown in the actor detail view.

As I said, interesting problem.
This also ties into remembering the query setting and the page while switching to grid view.

**Comment by sjclayton** [comment]
@curtwagner1984 Yes to clarify, you are correct in your interpretation of what I was saying... That is exactly what I meant.

Say you are on the Actors page and have Grid View enabled and you to go say page 2.. and then you click on a specific Actor, if you click the back button in your browser... when it returns to the Actors page it should still return to page 2 and not page 1 as page 2 was where you were before navigating forward.

**Comment by curtwagner1984** [comment]
Maybe a dirty workaround for this is to open new items in new tabs ?

**Comment by sjclayton** [comment]
@curtwagner1984 Could this be added, so that it automatically opens whatever is clicked on in a new tab...?
